name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME }}"
        echo "GCP_VM_HOST: ${{ secrets.GCP_VM_HOST }}"

    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Commands to copy the repository to the VM
          rsync -av --delete -e 'ssh -o StrictHostKeyChecking=no' $GITHUB_WORKSPACE/ bnsvishal@$34.70.224.200:/aml-project/
